export const KINDERGARTEN_SIGHT_WORDS: ReadonlySet<string> = new Set([
	'a',
	'and',
	'away',
	'big',
	'blue',
	'can',
	'come',
	'down',
	'find',
	'for',
	'funny',
	'go',
	'help',
	'here',
	'I',
	'in',
	'is',
	'it',
	'jump',
	'little',
	'look',
	'make',
	'me',
	'my',
	'not',
	'one',
	'play',
	'red',
	'run',
	'said',
	'see',
	'the',
	'three',
	'to',
	'two',
	'up',
	'we',
	'where',
	'yellow',
	'you',
]);

const FIRST_GRADE_EXTRA_WORDS: ReadonlySet<string> = new Set([
	'all',
	'am',
	'are',
	'at',
	'ate',
	'be',
	'black',
	'brown',
	'but',
	'came',
	'did',
	'do',
	'eat',
	'four',
	'get',
	'good',
	'have',
	'he',
	'into',
	'like',
	'must',
	'new',
	'no',
	'now',
	'on',
	'our',
	'out',
	'please',
	'pretty',
	'ran',
	'ride',
	'saw',
	'say',
	'she',
	'so',
	'soon',
	'that',
	'there',
	'they',
	'this',
	'too',
	'under',
	'want',
	'was',
	'well',
	'went',
	'what',
	'white',
	'who',
	'will',
	'with',
]);

export const FIRST_GRADE_SIGHT_WORDS: ReadonlySet<string> = new Set([
	...KINDERGARTEN_SIGHT_WORDS,
	...FIRST_GRADE_EXTRA_WORDS,
]);

// These constraints are primarily for reference or potentially for validation logic
// The actual prompt construction might embed the word lists directly or use the descriptions.
export const VOCABULARY_CONSTRAINTS = {
	kindergarten: {
		allowedWords: KINDERGARTEN_SIGHT_WORDS,
		maxNewWords: 5,
		description: `Use ONLY these sight words: ${Array.from(KINDERGARTEN_SIGHT_WORDS).join(', ')}. You may introduce up to 5 simple new words that a child can sound out. Keep sentences very short. Repeat new words.`,
	},
	firstGrade: {
		allowedWords: FIRST_GRADE_SIGHT_WORDS,
		maxNewWords: 8,
		description: `Use the Kindergarten words plus: ${Array.from(FIRST_GRADE_EXTRA_WORDS).join(', ')}. You may introduce up to 8 simple new words. Keep sentences short. Repeat new words.`,
	},
} as const; // Use 'as const' for stronger typing
